[package]
name = "otp-starter"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-cli = "0.1.0"
java-locator = "0.1.3"
toml = "0.5.10"
serde = "1.0"
serde_derive = "1.0"
